services:
  - type: web
    name: trsh-kpi
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/kpi-1.0.0.jar
    envVars:
      - key: DB_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: H2_CONSOLE
        value: false
