server.port = 8080

#database configuration 
spring.datasource.url=jdbc:h2:mem:trshkpi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=TRSHACADEMY
spring.datasource.password=YAC2026

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
sring.jpa.show-sql=false

#Browser console (access at Http://localhost:8080)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring,h2,console.settings.web-allow-others=false